name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-pnpm-project

      - name: Build project
        run: pnpm run build

      - name: Get latest commit message
        id: commit_message
        run: |
          message="$(git log -1 --pretty=%s)"
          echo "message=$message" >> "$GITHUB_OUTPUT"

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          commit_message: ${{ steps.commit_message.outputs.message }}
