name: PR Quality Checks

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  quality:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-pnpm-project

      - name: Run ESLint
        run: pnpm run lint

      - name: Run Prettier check
        run: pnpm run prettier

      - name: Run TypeScript check
        run: pnpm run check
